export VM_MGM_BRIDGE_DISABLE=${VM_MGM_BRIDGE_DISABLE:-false}
export VM_CTL_BRIDGE_DISABLE=${VM_CTL_BRIDGE_DISABLE:-false}
export VM_MGM_BRIDGE_NAME=${VM_MGM_BRIDGE_NAME:-"br-mgm"}
export VM_CTL_BRIDGE_NAME=${VM_CTL_BRIDGE_NAME:-"br-ctl"}
export VM_MGM_NETWORK_NAME=${VM_MGM_NETWORK_NAME:-"mgm_network"}
export VM_CTL_NETWORK_NAME=${VM_CTL_NETWORK_NAME:-"ctl_network"}
export VM_MEM_KB=${VM_MEM_KB:-"12589056"}
export VM_CPUS=${VM_CPUS:-"4"}
# optional params if you won't use bridge on host
export VM_MGM_NETWORK_GATEWAY=${VM_MGM_NETWORK_GATEWAY:-"192.168.56.1"}
export VM_MGM_NETWORK_MASK=${VM_MGM_NETWORK_MASK:-"255.255.255.0"}
export VM_CTL_NETWORK_GATEWAY=${VM_CTL_NETWORK_GATEWAY:-"192.168.57.1"}
export VM_CTL_NETWORK_MASK=${VM_CTL_NETWORK_MASK:-"255.255.255.0"}
# optional params if you want enable slave vm
export SLAVE_VM_MEM_KB=${SLAVE_VM_MEM_KB:-"16777216"}
export SLAVE_VM_CPUS=${SLAVE_VM_CPUS:-"4"}
export SLAVE_VM_DISK_SIZE=${SLAVE_VM_DISK_SIZE:-"50G"}